"""
Spec-Kit SDD Tools Registry.

Registers four tools that implement the spec-kit Spec-Driven Development pipeline:
  speckit_specify  - save spec.md to S3
  speckit_plan     - save plan.md to S3
  speckit_tasks    - save tasks.md to S3
  speckit_commit   - read from S3 and commit to GitHub
"""

import logging
from typing import Any

logger = logging.getLogger(__name__)


def register_speckit_tools(registry) -> None:
    """Register all spec-kit SDD tools with the ADK tool registry."""
    from src.services.agents.internal_tools.speckit_tools import (
        internal_speckit_commit,
        internal_speckit_plan,
        internal_speckit_specify,
        internal_speckit_tasks,
    )

    async def speckit_specify_wrapper(config: dict[str, Any] | None = None, **kwargs):
        runtime_context = config.get("_runtime_context") if config else None
        return await internal_speckit_specify(
            feature_id=kwargs.get("feature_id", ""),
            spec_content=kwargs.get("spec_content", ""),
            repo_url=kwargs.get("repo_url"),
            config=config,
            runtime_context=runtime_context,
        )

    async def speckit_plan_wrapper(config: dict[str, Any] | None = None, **kwargs):
        runtime_context = config.get("_runtime_context") if config else None
        return await internal_speckit_plan(
            feature_id=kwargs.get("feature_id", ""),
            plan_content=kwargs.get("plan_content", ""),
            config=config,
            runtime_context=runtime_context,
        )

    async def speckit_tasks_wrapper(config: dict[str, Any] | None = None, **kwargs):
        runtime_context = config.get("_runtime_context") if config else None
        return await internal_speckit_tasks(
            feature_id=kwargs.get("feature_id", ""),
            tasks_content=kwargs.get("tasks_content", ""),
            config=config,
            runtime_context=runtime_context,
        )

    async def speckit_commit_wrapper(config: dict[str, Any] | None = None, **kwargs):
        runtime_context = config.get("_runtime_context") if config else None
        return await internal_speckit_commit(
            filename=kwargs.get("filename", ""),
            s3_key=kwargs.get("s3_key", ""),
            repo=kwargs.get("repo", ""),
            branch=kwargs.get("branch", "specs"),
            path=kwargs.get("path"),
            config=config,
            runtime_context=runtime_context,
        )

    registry.register_tool(
        name="speckit_specify",
        description=(
            "Save agent-generated spec markdown to S3 and return a presigned download URL.\n\n"
            "IMPORTANT: Generate the full spec_content BEFORE calling this tool.\n\n"
            "spec_content MUST include these sections:\n"
            "  ## Overview\n"
            "  ## Problem Statement\n"
            "  ## User Stories\n"
            "  ## Functional Requirements\n"
            "  ## Non-Functional Requirements\n"
            "  ## Out of Scope\n"
            "  ## Open Questions  (use [NEEDS CLARIFICATION] for unresolved items)\n\n"
            "feature_id format: FEAT-NNNN (e.g. FEAT-0001). Assign sequentially."
        ),
        parameters={
            "type": "object",
            "properties": {
                "feature_id": {
                    "type": "string",
                    "description": "Feature identifier in FEAT-NNNN format (e.g. 'FEAT-0001')",
                },
                "spec_content": {
                    "type": "string",
                    "description": "Full spec markdown content generated by the agent",
                },
                "repo_url": {
                    "type": "string",
                    "description": "Optional repository URL for metadata (e.g. 'https://github.com/acme/project')",
                },
            },
            "required": ["feature_id", "spec_content"],
        },
        function=speckit_specify_wrapper,
        tool_category="speckit",
    )

    registry.register_tool(
        name="speckit_plan",
        description=(
            "Save agent-generated implementation plan markdown to S3 and return a presigned download URL.\n\n"
            "IMPORTANT: Generate the full plan_content BEFORE calling this tool.\n\n"
            "plan_content MUST include these sections:\n"
            "  ## Approaches Considered  (2-3 options with trade-offs)\n"
            "  ## Chosen Approach with Rationale\n"
            "  ## Tech Stack\n"
            "  ## Data Model Changes\n"
            "  ## API Contracts\n"
            "  ## Test Scenarios\n\n"
            "Use the same feature_id returned by speckit_specify."
        ),
        parameters={
            "type": "object",
            "properties": {
                "feature_id": {
                    "type": "string",
                    "description": "Feature identifier matching the spec (e.g. 'FEAT-0001')",
                },
                "plan_content": {
                    "type": "string",
                    "description": "Full implementation plan markdown generated by the agent",
                },
            },
            "required": ["feature_id", "plan_content"],
        },
        function=speckit_plan_wrapper,
        tool_category="speckit",
    )

    registry.register_tool(
        name="speckit_tasks",
        description=(
            "Save agent-generated task list markdown to S3 and return a presigned download URL.\n\n"
            "IMPORTANT: Generate the full tasks_content BEFORE calling this tool.\n\n"
            "Each task in tasks_content MUST include:\n"
            "  - Task ID: TASK-NNN\n"
            "  - Title\n"
            "  - Description\n"
            "  - Dependencies: list of TASK-NNN IDs (or 'none')\n"
            "  - Parallelizable: true or false\n\n"
            "Use the same feature_id from speckit_specify."
        ),
        parameters={
            "type": "object",
            "properties": {
                "feature_id": {
                    "type": "string",
                    "description": "Feature identifier matching the spec (e.g. 'FEAT-0001')",
                },
                "tasks_content": {
                    "type": "string",
                    "description": "Full task list markdown generated by the agent",
                },
            },
            "required": ["feature_id", "tasks_content"],
        },
        function=speckit_tasks_wrapper,
        tool_category="speckit",
    )

    registry.register_tool(
        name="speckit_commit",
        description=(
            "Commit a spec artifact from S3 to a GitHub repository.\n\n"
            "Reads the file from S3 using s3_key (returned by speckit_specify/plan/tasks), "
            "then commits it to the given repo and branch using the tenant's connected GitHub OAuth token.\n\n"
            "Call this three times (once per artifact) after the user confirms they want to commit.\n\n"
            "Requires: GitHub OAuth app connected in Settings > OAuth Apps."
        ),
        parameters={
            "type": "object",
            "properties": {
                "filename": {
                    "type": "string",
                    "description": "Filename to use in the commit (e.g. 'spec.md', 'plan.md', 'tasks.md')",
                },
                "s3_key": {
                    "type": "string",
                    "description": "S3 object key from the speckit_specify/plan/tasks response",
                },
                "repo": {
                    "type": "string",
                    "description": "GitHub repository in owner/repo format (e.g. 'acme/my-project')",
                },
                "branch": {
                    "type": "string",
                    "description": "Target branch name (default: 'specs')",
                    "default": "specs",
                },
                "path": {
                    "type": "string",
                    "description": "Directory path in the repo (default: derived from feature_id, e.g. 'specs/FEAT-0001')",
                },
            },
            "required": ["filename", "s3_key", "repo"],
        },
        function=speckit_commit_wrapper,
        tool_category="speckit",
    )

    logger.info("Registered 4 spec-kit SDD tools")
