"""
Spec-Kit SDD Tools for Synkora Agents.

Persistence-only tools that upload agent-generated spec artifacts to S3
and optionally commit them to GitHub. The agent (LLM) generates all markdown
content; these tools handle storage and identity.
"""

import base64
import logging
from typing import Any

import httpx

from src.services.agents.internal_tools.github_auth_helper import get_github_token_from_context
from src.services.storage.s3_storage import get_s3_storage

logger = logging.getLogger(__name__)

_S3_EXPIRY = 86400 * 7  # 7 days


def _get_tenant_id(config: dict[str, Any] | None) -> str:
    """Extract tenant_id string from runtime context, falling back to 'unknown'."""
    if config:
        rc = config.get("_runtime_context")
        if rc and getattr(rc, "tenant_id", None):
            return str(rc.tenant_id)
    return "unknown"


def _s3_key(tenant_id: str, feature_id: str, filename: str) -> str:
    return f"speckit/{tenant_id}/{feature_id}/{filename}"


async def _upload_markdown(tenant_id: str, feature_id: str, filename: str, content: str) -> dict[str, Any]:
    """Upload markdown string to S3, return s3_key and presigned URL. Raises on failure."""
    s3 = get_s3_storage()
    key = _s3_key(tenant_id, feature_id, filename)
    s3.upload_file(
        file_content=content.encode("utf-8"),
        key=key,
        content_type="text/markdown",
    )
    url = s3.generate_presigned_url(key=key, expiration=_S3_EXPIRY)
    return {"s3_key": key, "s3_url": url}


async def internal_speckit_specify(
    feature_id: str,
    spec_content: str,
    repo_url: str | None = None,
    config: dict[str, Any] | None = None,
    runtime_context: Any = None,
) -> dict[str, Any]:
    """
    Save an agent-generated spec to S3 and return a presigned download URL.

    The agent must generate spec_content before calling this tool.
    spec_content must include these sections:
      Overview | Problem Statement | User Stories | Functional Requirements |
      Non-Functional Requirements | Out of Scope | Open Questions
      (use [NEEDS CLARIFICATION] for unresolved items)

    Args:
        feature_id: Feature identifier in FEAT-NNNN format (e.g. "FEAT-0001")
        spec_content: Full spec markdown generated by the agent
        repo_url: Optional repository URL stored as metadata
        config: Tool config dict containing _runtime_context
        runtime_context: Unused (context comes via config)

    Returns:
        {"filename", "feature_id", "s3_url", "s3_key"} on success
        {"filename", "feature_id", "content", "storage_error": True} if S3 fails
        {"error": str} if input validation fails
    """
    if not spec_content or not spec_content.strip():
        return {"error": "spec_content is required and must not be empty"}
    if not feature_id or not feature_id.strip():
        return {"error": "feature_id is required"}

    tenant_id = _get_tenant_id(config)
    filename = "spec.md"

    try:
        upload = await _upload_markdown(tenant_id, feature_id, filename, spec_content)
        return {
            "filename": filename,
            "feature_id": feature_id,
            "s3_url": upload["s3_url"],
            "s3_key": upload["s3_key"],
        }
    except Exception as e:
        logger.error(f"speckit_specify S3 upload failed: {e}", exc_info=True)
        return {
            "filename": filename,
            "feature_id": feature_id,
            "content": spec_content,
            "storage_error": True,
            "storage_error_message": str(e),
        }


async def internal_speckit_plan(
    feature_id: str,
    plan_content: str,
    config: dict[str, Any] | None = None,
    runtime_context: Any = None,
) -> dict[str, Any]:
    """
    Save an agent-generated implementation plan to S3.

    The agent must generate plan_content before calling this tool.
    plan_content must include these sections:
      Approaches Considered (2-3 options with trade-offs) | Chosen Approach with Rationale |
      Tech Stack | Data Model Changes | API Contracts | Test Scenarios

    Args:
        feature_id: Feature identifier matching the spec (e.g. "FEAT-0001")
        plan_content: Full plan markdown generated by the agent
        config: Tool config dict containing _runtime_context
        runtime_context: Unused (context comes via config)

    Returns:
        {"filename", "feature_id", "s3_url", "s3_key"} on success
        {"filename", "feature_id", "content", "storage_error": True} if S3 fails
        {"error": str} if input validation fails
    """
    if not plan_content or not plan_content.strip():
        return {"error": "plan_content is required and must not be empty"}
    if not feature_id or not feature_id.strip():
        return {"error": "feature_id is required"}

    tenant_id = _get_tenant_id(config)
    filename = "plan.md"

    try:
        upload = await _upload_markdown(tenant_id, feature_id, filename, plan_content)
        return {
            "filename": filename,
            "feature_id": feature_id,
            "s3_url": upload["s3_url"],
            "s3_key": upload["s3_key"],
        }
    except Exception as e:
        logger.error(f"speckit_plan S3 upload failed: {e}", exc_info=True)
        return {
            "filename": filename,
            "feature_id": feature_id,
            "content": plan_content,
            "storage_error": True,
            "storage_error_message": str(e),
        }


async def internal_speckit_tasks(
    feature_id: str,
    tasks_content: str,
    config: dict[str, Any] | None = None,
    runtime_context: Any = None,
) -> dict[str, Any]:
    """
    Save an agent-generated task list to S3.

    The agent must generate tasks_content before calling this tool.
    Each task in tasks_content must include:
      Task ID (TASK-NNN) | Title | Description | Dependencies (list) | Parallelizable (bool)

    Args:
        feature_id: Feature identifier matching the spec (e.g. "FEAT-0001")
        tasks_content: Full task list markdown generated by the agent
        config: Tool config dict containing _runtime_context
        runtime_context: Unused (context comes via config)

    Returns:
        {"filename", "feature_id", "s3_url", "s3_key"} on success
        {"filename", "feature_id", "content", "storage_error": True} if S3 fails
        {"error": str} if input validation fails
    """
    if not tasks_content or not tasks_content.strip():
        return {"error": "tasks_content is required and must not be empty"}
    if not feature_id or not feature_id.strip():
        return {"error": "feature_id is required"}

    tenant_id = _get_tenant_id(config)
    filename = "tasks.md"

    try:
        upload = await _upload_markdown(tenant_id, feature_id, filename, tasks_content)
        return {
            "filename": filename,
            "feature_id": feature_id,
            "s3_url": upload["s3_url"],
            "s3_key": upload["s3_key"],
        }
    except Exception as e:
        logger.error(f"speckit_tasks S3 upload failed: {e}", exc_info=True)
        return {
            "filename": filename,
            "feature_id": feature_id,
            "content": tasks_content,
            "storage_error": True,
            "storage_error_message": str(e),
        }


async def internal_speckit_commit(
    filename: str,
    s3_key: str,
    repo: str,
    branch: str = "specs",
    path: str | None = None,
    config: dict[str, Any] | None = None,
    runtime_context: Any = None,
) -> dict[str, Any]:
    """
    Commit a spec artifact from S3 to a GitHub repository.

    Reads the file from S3 by key, then commits it to the given repo/branch
    using the tenant's connected GitHub OAuth token.

    Args:
        filename: Filename to use in the commit (e.g. "spec.md")
        s3_key: S3 object key to read content from (returned by speckit_specify/plan/tasks)
        repo: GitHub repository in owner/repo format (e.g. "acme/my-project")
        branch: Target branch name (default: "specs")
        path: Directory path in the repo (default: derived from feature_id in s3_key)
        config: Tool config dict containing _runtime_context
        runtime_context: Unused (context comes via config)

    Returns:
        {"commit_url", "file_url", "s3_url", "repo", "branch", "path"} on success
        {"error": str} on failure
    """
    if not filename or not filename.strip():
        return {"error": "filename is required"}
    if not s3_key or not s3_key.strip():
        return {"error": "s3_key is required"}
    if not repo or "/" not in repo:
        return {"error": "repo must be in owner/repo format (e.g. 'acme/my-project')"}

    rc = config.get("_runtime_context") if config else None

    token = await get_github_token_from_context(rc, tool_name="speckit_commit")
    if not token:
        return {"error": "No GitHub OAuth app connected for this tenant. Connect GitHub in Settings > OAuth Apps."}

    # Read content from S3
    try:
        s3 = get_s3_storage()
        raw_content = s3.download_file(s3_key)
        content_str = raw_content.decode("utf-8") if isinstance(raw_content, bytes) else raw_content
    except Exception as e:
        logger.error(f"speckit_commit S3 read failed for key {s3_key}: {e}", exc_info=True)
        return {"error": f"Failed to read file from S3: {str(e)}"}

    # Derive commit path from s3_key: speckit/{tenant}/{feature_id}/filename
    owner, repo_name = repo.split("/", 1)
    if path is None:
        parts = s3_key.split("/")
        feature_id = parts[2] if len(parts) >= 4 else "unknown"
        path = f"specs/{feature_id}"
    file_path_in_repo = f"{path.strip('/')}/{filename}"

    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }

    async with httpx.AsyncClient(timeout=30.0) as client:
        # Ensure branch exists
        branch_resp = await client.get(
            f"https://api.github.com/repos/{owner}/{repo_name}/git/ref/heads/{branch}",
            headers=headers,
        )

        if branch_resp.status_code == 404:
            # Get default branch SHA to base the new branch on
            repo_resp = await client.get(
                f"https://api.github.com/repos/{owner}/{repo_name}",
                headers=headers,
            )
            if repo_resp.status_code != 200:
                return {"error": f"GitHub repo not found or no access: {repo_resp.text}"}
            default_branch = repo_resp.json().get("default_branch", "main")
            sha_resp = await client.get(
                f"https://api.github.com/repos/{owner}/{repo_name}/git/ref/heads/{default_branch}",
                headers=headers,
            )
            if sha_resp.status_code != 200:
                return {"error": f"Could not get SHA for default branch: {sha_resp.text}"}
            base_sha = sha_resp.json()["object"]["sha"]
            create_resp = await client.post(
                f"https://api.github.com/repos/{owner}/{repo_name}/git/refs",
                headers=headers,
                json={"ref": f"refs/heads/{branch}", "sha": base_sha},
            )
            if create_resp.status_code not in (200, 201):
                return {"error": f"Failed to create branch '{branch}': {create_resp.text}"}

        elif branch_resp.status_code != 200:
            return {"error": f"GitHub API error checking branch: {branch_resp.text}"}

        # Check if file already exists (need its SHA for update)
        existing_sha: str | None = None
        file_check_resp = await client.get(
            f"https://api.github.com/repos/{owner}/{repo_name}/contents/{file_path_in_repo}",
            headers=headers,
            params={"ref": branch},
        )
        if file_check_resp.status_code == 200:
            existing_sha = file_check_resp.json().get("sha")

        # Commit the file
        commit_payload: dict[str, Any] = {
            "message": f"docs: add {filename} for {path}",
            "content": base64.b64encode(content_str.encode("utf-8")).decode("ascii"),
            "branch": branch,
        }
        if existing_sha:
            commit_payload["sha"] = existing_sha

        put_resp = await client.put(
            f"https://api.github.com/repos/{owner}/{repo_name}/contents/{file_path_in_repo}",
            headers=headers,
            json=commit_payload,
        )
        if put_resp.status_code not in (200, 201):
            return {"error": f"GitHub commit failed: {put_resp.text}"}

        resp_data = put_resp.json()
        commit_url = resp_data.get("commit", {}).get("html_url", "")
        file_url = resp_data.get("content", {}).get("html_url", "")

        # Regenerate presigned URL for convenience
        try:
            s3_presigned = get_s3_storage().generate_presigned_url(key=s3_key, expiration=_S3_EXPIRY)
        except Exception:
            s3_presigned = None

        logger.info(f"speckit_commit: committed {file_path_in_repo} to {repo}@{branch}")
        return {
            "commit_url": commit_url,
            "file_url": file_url,
            "s3_url": s3_presigned,
            "repo": repo,
            "branch": branch,
            "path": file_path_in_repo,
        }
